### ISSUE TITLE
TODO: Future iterations include tools for login & account management on AWS & integrate directly into Engine

### ISSUE THREAD

**Issue by arcman7** [Hines94/BabylonBurst#1]
Any chance we can collab on this? We (me and two other engineers) are in dire need of this game editor app.

**Comment by Hines94** [comment]
Hey sorry I missed this! @arcman7  If you are keen then absolutely, the more hands the better. Things have improved a bit recently but there is a bunch of stuff like the login that could be easily added with some time!

**Comment by arcman7** [comment]
I'm gonna dm you on the bjs forum
